server {
    listen 80;
    server_name migiromotors.com.au www.migiromotors.com.au;

    root /var/www/migiromotors;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
